# Configure a course calendar
# Used for title of web page
courseTitle = "Latin 101, section 2, F'22"
# YYYY-MM-DD
firstDay = "2022-08-31"
lastDay = "2022-12-17"

# Pattern of class meetings: "mwf", "tt" or "wf"
schedule = "mwf"

# Number of weeks the calendar should run for
totalWeeks =  14

fixedDates = [
  ["2022-08-29", "Advising: no classes."],
  ["2022-10-07",  "Last class before fall break."],
  ["2022-10-17",  "Classes resume."],
  ["2022-11-22",  "Last class before Thanksgiving break."],
  ["2022-11-28",  "Classes resume."],
  ["2022-12-09",  "Last day of classes."],
  ["2022-12-10",  "Study period begins."],
  ["2022-12-13",  "Final examinations begin."],


  ["2022-10-25",  "âœï¸ First reflection exercise."],
  ["2022-12-07",  "âœï¸ Second reflection exercise."],

    ["2022-09-15",  "ğŸ“œ Mastering [unit 1](https://hellenike.github.io/textbook/practice/module1/portfolio/mastery/) due."],
    ["2022-09-22",  "ğŸ“œ [Reading assignment](https://hellenike.github.io/textbook/practice/module1/portfolio/reading/) 1 due."],
    ["2022-09-29",  "ğŸ“œ [Composition 1](https://hellenike.github.io/textbook/practice/module1/portfolio/composition/) due."],

    ["2022-10-18",  "ğŸ“œ Mastering [unit 2](https://hellenike.github.io/textbook/practice/module2/portfolio/mastery/) forms due."],
    ["2022-10-20",  "ğŸ“œ [Reading assignment](https://hellenike.github.io/textbook/practice/module2/portfolio/reading/) 2 due."],
    ["2022-10-27",  "ğŸ“œ [Composition 2](https://hellenike.github.io/textbook/practice/module2/portfolio/composition/) due."],

    ["2022-11-15",  "ğŸ“œ Mastering [unit 3](https://hellenike.github.io/textbook/practice/module3/portfolio/mastery/) forms due."],
    ["2022-11-17",  "ğŸ“œ [Reading assignment](https://hellenike.github.io/textbook/practice/module3/portfolio/reading/) 3 due."],
    ["2022-11-20",  "ğŸ“œ Composition 3 due."],


    ["2022-10-21",  "âš ï¸ **Last day to submit revisions of Module 1 assignments**."],
    ["2022-12-02",  "âš ï¸ **Last day to submit revisions of Module 2 assignments**."],
    ["2022-12-12",  "âš ï¸ **Last day to submit revisions of Module 3 and 4 assignments**.."],
]




